### ISSUE TITLE
Adding a platform?

### ISSUE THREAD

**Issue by TADadmin** [paralin/rtl8821au#4]
I'm trying to use an 8821A device with the Raspberry Pi 2 which as far as I understand is an ARMv7 architecture. Can that be added to the supported platforms? Or is one of the currently supported ARM platforms compatible with it?

**Comment by paralin** [comment]
We use it for ARM in Buildroot. See: https://github.com/paralin/buildroot/blob/master/package/rtl8821au/rtl8821au.mk
