### ISSUE TITLE
Can't find directory that exists?

### ISSUE THREAD

**Issue by rabinnh** [paralin/rtl8821au#5]
Actually tried this on both a Beaglebone Black ARM board, and then my regular x86_64 Desktop (Ubuntu 14.04).  IN both case set "CONFIG_RTL8821A=y", run make, and in both cases get the identical message:

make ARCH= CROSS_COMPILE= -C  M=/home/rabiinh/projects/rtl8821au  modules
make: **\* M=/home/rabinnh/projects/rtl8821au: No such file or directory.  Stop.
make: **\* [modules] Error 2

The directions are pretty straight forward.  What am I missing?

**Comment by paralin** [comment]
Hmm odd. However ARCH= should not be blank, nor should CROSS_COMPILE or -C

**Comment by rabinnh** [comment]
Sorry Christian, brain fart on my end.  I set the WIFI IC and for got the rest.  I was actually looking for a Platform of x86_64, but I guess the i386 covers it.

Curious how one could natively compile this on the target, for example the BeagleBone Black.  It looks like this Makefile is strictly designed for cross compiling with a toolchain.

**Comment by paralin** [comment]
Just compile it like you would on any computer onboard. If you have gcc installed on the beaglebone you'll be fine.
