### ISSUE TITLE
Compile error on kernel 4.4.9

### ISSUE THREAD

**Issue by phouverneyuff** [paralin/rtl8821au#6]
Hi there,

i'm compiling in kernel 4.4.9 using Fedora 23 and i'm getting the follow error:

`sudo make

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.4.9-300.fc23.x86_64/build M=/mnt/dados/backup-dell/drivers/rtl8821au  modules
make[1]: Entering directory '/usr/src/kernels/4.4.9-300.fc23.x86_64'
  CC [M]  /mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.o
In file included from /mnt/dados/backup-dell/drivers/rtl8821au/include/drv_types.h:65:0,
                 from /mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c:22:
/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c: In function ‘btinfo_evt_dump’:
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /_rtw_warn_on(1)_/; \
       ^
/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c:3293:2: note: in expansion of macro ‘DBG_871X_SEL_NL’
  DBG_871X_SEL_NL(sel, "cid:0x%02x, len:%u\n", info->cid, info->len);
  ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /_rtw_warn_on(1)_/; \
       ^
/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c:3296:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "byte2:%s%s%s%s%s%s%s%s\n"
   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /_rtw_warn_on(1)_/; \
       ^
/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c:3308:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "retry_cnt:%u\n", info->retry_cnt);
   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /_rtw_warn_on(1)_/; \
       ^
/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c:3311:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "rssi:%u\n", info->rssi);
   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:187:19: error: void value not ignored as it ought to be
  #define _seqdump seq_printf
                   ^
/mnt/dados/backup-dell/drivers/rtl8821au/include/rtw_debug.h:242:7: note: in expansion of macro ‘_seqdump’
    if(_seqdump(sel, fmt, ##arg)) /_rtw_warn_on(1)_/; \
       ^
/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.c:3314:3: note: in expansion of macro ‘DBG_871X_SEL_NL’
   DBG_871X_SEL_NL(sel, "byte5:%s%s\n"
   ^
scripts/Makefile.build:258: recipe for target '/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.o' failed
make[2]: **\* [/mnt/dados/backup-dell/drivers/rtl8821au/core/rtw_cmd.o] Error 1
Makefile:1388: recipe for target '_module_/mnt/dados/backup-dell/drivers/rtl8821au' failed
make[1]: **\* [_module_/mnt/dados/backup-dell/drivers/rtl8821au] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.4.9-300.fc23.x86_64'
Makefile:1545: recipe for target 'modules' failed
make: **\* [modules] Error 2
`

**Comment by paralin** [comment]
This is definitely an issue - let's get this patched up.

I'll have a look at it sometime this weekend. I wonder which kernel version
caused it to stop compiling?

**Comment by phouverneyuff** [comment]
Working using this driver compiling with dkms
https://github.com/diederikdehaas/rtl8812AU
